# Generated by Django 3.2.9 on 2021-11-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoissonsDiverses',
            fields=[
                ('id_boissons_diverses', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=45)),
                ('prix_de_vente', models.FloatField()),
            ],
            options={
                'db_table': 'boissons_diverses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bouteilles',
            fields=[
                ('id_bouteille', models.AutoField(primary_key=True, serialize=False)),
                ('num_bouteille', models.IntegerField(unique=True)),
                ('date_achat', models.DateTimeField()),
                ('prix_achat', models.FloatField()),
            ],
            options={
                'db_table': 'bouteilles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'commande',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id_date_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField()),
            ],
            options={
                'db_table': 'date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id_diplome', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'diplome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id_employe', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('adresse', models.CharField(max_length=45)),
                ('code_postal', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=45)),
                ('telephone', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'employe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('num_menu', models.IntegerField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=45)),
                ('prix_de_vente_menu', models.FloatField()),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id_plat', models.AutoField(primary_key=True, serialize=False)),
                ('num_plat', models.IntegerField(blank=True, null=True)),
                ('libelle_plat', models.CharField(max_length=45)),
                ('prix_de_vente_plat', models.FloatField()),
            ],
            options={
                'db_table': 'plat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('type_service', models.CharField(max_length=45)),
                ('designation_service', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id_table', models.AutoField(primary_key=True, serialize=False)),
                ('num_table', models.IntegerField(blank=True, null=True)),
                ('capacite', models.IntegerField()),
            ],
            options={
                'db_table': 'table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypePlat',
            fields=[
                ('id_type_plat', models.AutoField(primary_key=True, serialize=False)),
                ('designation_type_plat', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'type_plat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id_vin', models.AutoField(primary_key=True, serialize=False)),
                ('num_vin', models.IntegerField(blank=True, null=True)),
                ('millesime', models.IntegerField()),
                ('prix_de_vente', models.FloatField()),
            ],
            options={
                'db_table': 'vin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viticulteur',
            fields=[
                ('id_viticulteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_viticulteur', models.CharField(max_length=45)),
                ('prenom_viticulteur', models.CharField(max_length=45, unique=True)),
                ('adresse_viticulteur', models.CharField(max_length=45)),
                ('code_postal', models.CharField(max_length=45)),
                ('ville', models.CharField(max_length=45)),
                ('telephone', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'viticulteur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoissonsCommande',
            fields=[
                ('id_boissons_diverses', models.OneToOneField(db_column='id_boissons_diverses', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='resto_app.boissonsdiverses')),
                ('quantite', models.IntegerField()),
            ],
            options={
                'db_table': 'boissons_commande',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiplomePossedePar',
            fields=[
                ('id_diplome', models.OneToOneField(db_column='id_diplome', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='resto_app.diplome')),
                ('date_obtention', models.DateTimeField()),
            ],
            options={
                'db_table': 'diplome_possede_par',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatMenu',
            fields=[
                ('id_plat', models.OneToOneField(db_column='id_plat', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='resto_app.plat')),
            ],
            options={
                'db_table': 'plat_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VinsCommande',
            fields=[
                ('id_vin', models.OneToOneField(db_column='id_vin', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='resto_app.vin')),
            ],
            options={
                'db_table': 'vins_commande',
                'managed': False,
            },
        ),
    ]
